### ISSUE TITLE
IndexError from apicapi with AIM Unified mode with OpenStack

### ISSUE THREAD

**Issue by mmnelemane** [noironetworks/apicapi#89]
While trying to setup basic openstack integration setup (1 controller and 2 computes), I am following the documentation from https://github.com/noironetworks/opflex-documentation. This test was one using Newton an Pike OpenStack Releases and corresponding plugin releases from github.com/noironetworks. The following steps works without error:

aimctl db-migration upgrade head
aimctl config update
aimctl infra create
aimctl manager load-daemons --enforce

Starting aim-aid service results in the following error from python-apicapi:

2018-10-30 06:12:54.636 27610 CRITICAL aim [-] Unhandled error: IndexError: deque index out of range
2018-10-30 06:12:54.636 27610 ERROR aim Traceback (most recent call last):
2018-10-30 06:12:54.636 27610 ERROR aim   File "/usr/bin/aim-aid", line 10, in <module>
2018-10-30 06:12:54.636 27610 ERROR aim     sys.exit(aid())
2018-10-30 06:12:54.636 27610 ERROR aim   File "/usr/lib/python2.7/site-packages/aim/tools/services/aid.py", line 22, in aid
2018-10-30 06:12:54.636 27610 ERROR aim     service.main()
2018-10-30 06:12:54.636 27610 ERROR aim   File "/usr/lib/python2.7/site-packages/aim/agent/aid/service.py", line 304, in main
2018-10-30 06:12:54.636 27610 ERROR aim     agent = AID(aim_cfg.CONF)
2018-10-30 06:12:54.636 27610 ERROR aim   File "/usr/lib/python2.7/site-packages/aim/agent/aid/service.py", line 80, in __init__
2018-10-30 06:12:54.636 27610 ERROR aim     self.conf_manager, self.multiverse)},
2018-10-30 06:12:54.636 27610 ERROR aim   File"/usr/lib/python2.7/site-packages/aim/agent/aid/universes/aci/aci_universe.py", line 286, in initialize
2018-10-30 06:12:54.636 27610 ERROR aim     aci_tenant.get_children_mos(self.aci_session, 'tn-common')
2018-10-30 06:12:54.636 27610 ERROR aim   File"/usr/lib/python2.7/site-packages/aim/agent/aid/universes/aci/tenant.py", line 74, in get_children_mos
2018-10-30 06:12:54.636 27610 ERROR aim     'target-subtree-class=%s' % mo_name)
2018-10-30 06:12:54.636 27610 ERROR aim   File "/usr/lib/python2.7/site-packages/apicapi/apic_client.py", line 662, in GET
2018-10-30 06:12:54.636 27610 ERROR aim     return self._send(self.session.get, url, data=data)
2018-10-30 06:12:54.636 27610 ERROR aim   File "/usr/lib/python2.7/site-packages/apicapi/apic_client.py", line 562, in _send
2018-10-30 06:12:54.636 27610 ERROR aim     response = self._do_request(request, url, cookies=self.cookie)
2018-10-30 06:12:54.636 27610 ERROR aim   File "/usr/lib/python2.7/site-packages/apicapi/apic_client.py", line 510, in _do_request
2018-10-30 06:12:54.636 27610 ERROR aim     return request(self.api_base[0] + url, verify=self.verify, **kwargs)
2018-10-30 06:12:54.636 27610 ERROR aim IndexError: deque index out of range
2018-10-30 06:12:54.636 27610 ERROR aim

I might guess that this issue could be due to an inaccessible configuration from aim.conf within apicapi, but I could be wrong.
Any clue or work-around to proceed further would be helpful. In addition, please also point me to a more relevant documentation for this integration (if I am using neither of RH OSP Director or Juju Charms).

**Comment by mmnelemane** [comment]
@tbachman: sorry for the delay in reply. 
these options are not missing from the aim.conf. I have the [apic] section with the following parameters filled up as below:

apic_hosts = xx.xxx.xx.221, xx.xxx.xx.222, xx.xxx.xx.223
apic_username = admin
apic_password = xxxxxxxx
apic_use_ssl = True
certificate_name = /etc/neutron/ssl/certs/signing_cert.pem
private_key_file = /etc/neutron/ssl/private/signing_key.pem

A few logs shows that the aci_universe.py does not receive the list of apic_hosts.
